### ISSUE TITLE
magento tax issue

### ISSUE THREAD

**Issue by ajbird2** [danslo/hhvm#31] opened 2014-02-04 15:01 UTC
I am seeing some strange tax related issues with HHVM.

Here is the correct tax as shown with Nginx > php-fpm
http://screencast.com/t/gV0ZuX7g

Immediately switch to HHVM and refresh:
http://screencast.com/t/sw05brthT

ie the VAT is no longer included in the Grand total.

**Comment by jaredkipe** [comment] 2014-02-06 19:05
Can you check out using both completely (i.e. not switching between the two)
See if both orders/invoices are created with the correct totals.

**Comment by ajbird2** [comment] 2014-02-07 17:52
The order arrives exactly as formatted in the cart ie vat missing in grand total

**Comment by jaredkipe** [comment] 2014-02-07 20:55
Did you try deleting the session and maybe the quote to see if this has to do with some serialized data differences between HHVM and PHP-FPM.

**Comment by danslo** [comment] 2014-02-07 20:57
Yes, please use something isolated. Try an incognito window and see if you can reproduce the problem.

**Comment by cscd98** [comment] 2014-03-06 10:10
We are also having this issue

**Comment by cscd98** [comment] 2014-03-11 11:24
I can replicate this issue now. For example:

Our prices are inclusive of VAT. If I add a product to to the basket at £169.99 the price displayed in the line items fine. However the net total is displayed as £169.99 when it should be without VAT (deduct 20%).

It is then adding VAT back on top of that £169.99 in the grand total! The amount of VAT is also displayed incorrectly, it should be 33.998 where it is actually displaying 28.33.

I have rebuilt HHVM from today so it is a bug in the current master.

**Comment by danslo** [comment] 2014-03-13 14:08
@craigcarnell So how do _I_ reproduce it?

What are the exact steps I need to take (on a clean install)?

**Comment by danslo** [comment] 2014-03-13 14:24
FYI, this is how it works for me:

<img src="http://i.imgur.com/wIDcbkM.png" />
<img src="http://i.imgur.com/yCgerxY.png" />

**Comment by cscd98** [comment] 2014-03-14 12:06
The admin shows the correct price, but the totals in the basket are still incorrect, TAX is added back on top of the item which already includes TAX.

Could it be a locale issue? Or a simplexml issue?

**Comment by danslo** [comment] 2014-03-14 12:15
It could be anything at this point, and I won't be able to further comment on it unless I can reproduce the problem :-(

**Comment by cscd98** [comment] 2014-03-20 10:08
Hi Daniel, Apologies for the late reply. We are using UK prices (GBP) - not sure if this makes a difference or not. I will attach my screenshots for our settings as below!

Here is my product (under Catalog->Manage Products->Edit Product->Price tab:

![screen shot 2014-03-20 at 10 06 28](https://f.cloud.github.com/assets/1188869/2470712/7a159bb4-b017-11e3-861d-6449354ec2e7.png)

Here is my tax settings:

![screen shot 2014-03-20 at 10 05 15](https://f.cloud.github.com/assets/1188869/2470704/58a0f6cc-b017-11e3-9922-43392b3da453.png)

![screen shot 2014-03-20 at 10 05 56](https://f.cloud.github.com/assets/1188869/2470709/66ee04e0-b017-11e3-94d4-44ecbf03eedd.png)

Here is my basket:

![screen shot 2014-03-20 at 10 03 25](https://f.cloud.github.com/assets/1188869/2470699/3d24ca40-b017-11e3-8e54-db7e4db39394.png)

As you can see from the basket, it's adding tax (VAT) on top when it's already included.

**Comment by danslo** [comment] 2014-03-21 15:38
Can't help you, works fine for me:

<img src="http://i.imgur.com/p9hqZBg.png" />
<img src="http://i.imgur.com/vWvgD1R.png" />

**Comment by cscd98** [comment] 2014-03-22 09:11
I'm off on holiday this week but I will try and setup a clean install or do some more debugging to help you find the issue.

**Comment by ajbird2** [comment] 2014-04-11 10:20
Have you tried on 3.0.0.0 yet?

**Comment by cscd98** [comment] 2014-04-11 11:48
I am just compiling from master at the moment and will let you know. Edit: Run time error with master, so no report yet :(

**Comment by danslo** [comment] 2014-04-19 16:53
Closing this in favor of tracking it upstream, see the referenced issue above.

**Closed as completed by danslo** 2014-04-19 16:53 UTC
