### ISSUE TITLE
magento2 - "session.save_path" is not a valid sessions-related ini 

### ISSUE THREAD

**Issue by cscd98** [danslo/hhvm#34] opened 2014-03-21 16:22 UTC
Clean install, no local.xml or config.xml. 

<?php echo session_save_path(); ?> gives out a empty string

```
cat 505141387252 
a:4:{i:0;s:64:""session.save_path" is not a valid sessions-related ini setting.";i:1;s:6109:"#0 /var/www/vhosts/magento2/releases/20140321145718/app/code/Magento/Core/Model/Session/Config.php(234): Magento\Core\Model\Session\Config->setStorageOption()
#1 /var/www/vhosts/magento2/releases/20140321145718/app/code/Magento/Core/Model/Session/Config.php(320): Magento\Core\Model\Session\Config->setOption()
#2 /var/www/vhosts/magento2/releases/20140321145718/app/code/Magento/Core/Model/Session/Config.php(160): Magento\Core\Model\Session\Config->setSavePath()
#3 (): Magento\Core\Model\Session\Config->__construct()
#4 /var/www/vhosts/magento2/releases/20140321145718/lib/Magento/ObjectManager/Factory/Factory.php(166): ReflectionClass->newInstanceArgs()
#5 /var/www/vhosts/magento2/releases/20140321145718/lib/Magento/ObjectManager/ObjectManager.php(87): Magento\ObjectManager\Factory\Factory->create()
#6 /var/www/vhosts/magento2/releases/20140321145718/lib/Magento/ObjectManager/Config/Argument/ObjectFactory.php(90): Magento\ObjectManager\ObjectManager->get()
#7 /var/www/vhosts/magento2/releases/20140321145718/lib/Magento/ObjectManager/Factory/Factory.php(112): Magento\ObjectManager\Config\Argument\ObjectFactory->create()
#8 /var/www/vhosts/magento2/releases/20140321145718/lib/Magento/ObjectManager/Factory/Factory.php(141): Magento\ObjectManager\Factory\Factory->_resolveArguments()
#9 /var/www/vhosts/magento2/releases/20140321145718/lib/Magento/ObjectManager/ObjectManager.php(87): Magento\ObjectManager\Factory\Factory->create()
#10 /var/www/vhosts/magento2/releases/20140321145718/lib/Magento/ObjectManager/Config/Argument/ObjectFactory.php(90): Magento\ObjectManager\ObjectManager->get()
#11 /var/www/vhosts/magento2/releases/20140321145718/lib/Magento/ObjectManager/Factory/Factory.php(112): Magento\ObjectManager\Config\Argument\ObjectFactory->create()
#12 /var/www/vhosts/magento2/releases/20140321145718/lib/Magento/ObjectManager/Factory/Factory.php(141): Magento\ObjectManager\Factory\Factory->_resolveArguments()
#13 /var/www/vhosts/magento2/releases/20140321145718/lib/Magento/ObjectManager/ObjectManager.php(87): Magento\ObjectManager\Factory\Factory->create()
#14 /var/www/vhosts/magento2/releases/20140321145718/lib/Magento/ObjectManager/Config/Argument/ObjectFactory.php(90): Magento\ObjectManager\ObjectManager->get()
#15 /var/www/vhosts/magento2/releases/20140321145718/lib/Magento/ObjectManager/Factory/Factory.php(112): Magento\ObjectManager\Config\Argument\ObjectFactory->create()
#16 /var/www/vhosts/magento2/releases/20140321145718/lib/Magento/ObjectManager/Factory/Factory.php(141): Magento\ObjectManager\Factory\Factory->_resolveArguments()
#17 /var/www/vhosts/magento2/releases/20140321145718/lib/Magento/ObjectManager/ObjectManager.php(74): Magento\ObjectManager\Factory\Factory->create()
#18 /var/www/vhosts/magento2/releases/20140321145718/lib/Magento/App/ActionFactory.php(52): Magento\ObjectManager\ObjectManager->create()
#19 /var/www/vhosts/magento2/releases/20140321145718/app/code/Magento/Core/App/Router/Base.php(313): Magento\App\ActionFactory->createController()
#20 /var/www/vhosts/magento2/releases/20140321145718/app/code/Magento/Core/App/Router/Base.php(150): Magento\Core\App\Router\Base->_matchController()
#21 /var/www/vhosts/magento2/releases/20140321145718/lib/Magento/App/FrontController.php(58): Magento\Core\App\Router\Base->match()
#22 (): Magento\App\FrontController->dispatch()
#23 /var/www/vhosts/magento2/shared/var/generation/Magento/App/FrontController/Interceptor.php(48): call_user_func_array()
#24 /var/www/vhosts/magento2/releases/20140321145718/lib/Magento/Interception/Chain/Chain.php(83): Magento\App\FrontController\Interceptor->___callParent()
#25 /var/www/vhosts/magento2/releases/20140321145718/lib/Magento/Interception/Chain/Chain.php(76): Magento\Interception\Chain\Chain->invokeNext()
#26 /var/www/vhosts/magento2/releases/20140321145718/app/code/Magento/Core/App/FrontController/Plugin/UrlRewrite.php(68): {closure}()
#27 (): Magento\Core\App\FrontController\Plugin\UrlRewrite->aroundDispatch()
#28 /var/www/vhosts/magento2/releases/20140321145718/lib/Magento/Interception/Chain/Chain.php(81): call_user_func_array()
#29 /var/www/vhosts/magento2/releases/20140321145718/lib/Magento/Interception/Chain/Chain.php(76): Magento\Interception\Chain\Chain->invokeNext()
#30 /var/www/vhosts/magento2/releases/20140321145718/app/code/Magento/Core/App/FrontController/Plugin/RequestPreprocessor.php(113): {closure}()
#31 (): Magento\Core\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch()
#32 /var/www/vhosts/magento2/releases/20140321145718/lib/Magento/Interception/Chain/Chain.php(81): call_user_func_array()
#33 /var/www/vhosts/magento2/releases/20140321145718/lib/Magento/Interception/Chain/Chain.php(76): Magento\Interception\Chain\Chain->invokeNext()
#34 /var/www/vhosts/magento2/releases/20140321145718/lib/Magento/Module/FrontController/Plugin/Install.php(82): {closure}()
#35 (): Magento\Module\FrontController\Plugin\Install->aroundDispatch()
#36 /var/www/vhosts/magento2/releases/20140321145718/lib/Magento/Interception/Chain/Chain.php(81): call_user_func_array()
#37 /var/www/vhosts/magento2/shared/var/generation/Magento/App/FrontController/Interceptor.php(88): Magento\Interception\Chain\Chain->invokeNext()
#38 /var/www/vhosts/magento2/releases/20140321145718/app/code/Magento/Core/App/FrontController/Plugin/DispatchExceptionHandler.php(73): {closure}()
#39 (): Magento\Core\App\FrontController\Plugin\DispatchExceptionHandler->aroundDispatch()
#40 /var/www/vhosts/magento2/shared/var/generation/Magento/App/FrontController/Interceptor.php(93): call_user_func_array()
#41 /var/www/vhosts/magento2/shared/var/generation/Magento/App/FrontController/Interceptor.php(115): Magento\App\FrontController\Interceptor->___call()
#42 /var/www/vhosts/magento2/releases/20140321145718/lib/Magento/App/Http.php(121): Magento\App\FrontController\Interceptor->dispatch()
#43 /var/www/vhosts/magento2/releases/20140321145718/lib/Magento/App/EntryPoint/EntryPoint.php(83): Magento\App\Http->launch()
#44 /var/www/vhosts/magento2/releases/20140321145718/index.php(37): Magento\App\EntryPoint\EntryPoint->run()
```

**Comment by danslo** [comment] 2014-03-21 16:38
I already fixed that in https://github.com/facebook/hhvm/pull/2075

Not merged yet, but closing this :-)

**Comment by cscd98** [comment] 2014-03-22 09:11
Nice one thanks

**Comment by niclashoyer** [comment] 2014-03-29 21:48
damn it, it just didn't make it into the 3.0.0 release :(

**Comment by cscd98** [comment] 2014-04-23 15:59
Still not working for me:

```
[Tue Apr 22 19:28:17 2014] [hphp] [15754:7f60af3ff700:2:000001] [] \nWarning: open(/var/www/vhosts/magento2-capistrano/releases/20140422192801/var/session/sess_7343663623030313932603935353431603832383939346163613437343167353, O_RDWR) failed: No such file or directory (2)
[Tue Apr 22 19:28:17 2014] [hphp] [15754:7f60af3ff700:2:000002] [] \nWarning: Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/var/www/vhosts/magento2-capistrano/releases/20140422192801/var/session) in /var/www/vhosts/magento2-capistrano/releases/20140422192801/lib/Magento/Session/SessionManager.php on line 125
```

**Comment by danslo** [comment] 2014-04-23 16:01
I'll re-open, with a sidenote that I won't be looking at this any time soon. Currently very focused on Magento 1.

**Comment by cscd98** [comment] 2014-05-06 15:58
No problem. I've tried files and db session handler and both same result.

**Comment by danslo** [comment] 2014-05-06 19:01
I had some time to look in to this. The problem is that Magento 2 deletes the var directory (which includes our session files). Apparently PHP can deal with this more gracefully.

Temporary solution is to just comment out that part of the code before installing:

``` diff
diff --git a/app/code/Magento/Install/App/Action/Plugin/Dir.php b/app/code/Magento/Install/App/Action/Plugin/Dir.php
index 46c58cf..f0f6b8e 100644
--- a/app/code/Magento/Install/App/Action/Plugin/Dir.php
+++ b/app/code/Magento/Install/App/Action/Plugin/Dir.php
@@ -80,7 +80,7 @@ class Dir
             foreach ($this->varDirectory->read() as $dir) {
                 if ($this->varDirectory->isDirectory($dir)) {
                     try {
-                        $this->varDirectory->delete($dir);
+                        // $this->varDirectory->delete($dir);
                     } catch (FilesystemException $exception) {
                         $this->logger->log($exception->getMessage());
                     }
```

I will still be closing this as a wont-fix because of Magento 2's volatile nature, the fact that it's probably undefined behavior, and that I don't really want to spend any time fixing the issue :-P

**Closed as completed by danslo** 2014-05-06 19:01 UTC
