### ISSUE TITLE
Controller Rewrites (in an extension's config.xml) aren't processed.

### ISSUE THREAD

**Issue by MattDunbar** [danslo/hhvm#5] opened 2013-08-14 10:29 UTC
Testable with this: https://github.com/BuildRX/mage-hhvm

Go to manage stores and hit save, you will get this error on HHVM:
HipHop Fatal error: preg_replace is not going to be supported: Modifier /e must be used with the form f("<replacement string>") or f("<replacement string>"); in app/code/core/Mage/Core/Helper/Abstract.php on line 238

If the rewrite loads successfully the save will succeed.  I can try to come up with a testcase thursday or friday if you don't have anything by then.

**Comment by danslo** [comment] 2013-08-14 16:19
Please clarify on this issue? When I place a die('called') in your StoreController _getHelper, it works just fine.

**Comment by danslo** [comment] 2013-08-14 16:22
In other words, the rewrite works for me. 

`The store view has been saved`

Are you absolutely sure you are using the latest version? Do:

``` sh
git fetch origin master
git stash
git reset --hard FETCH_HEAD
git stash pop
```

Closing this issue as it seems to work as intended. Please re-open if I missed something.

**Closed as completed by danslo** 2013-08-14 16:22 UTC

**Comment by MattDunbar** [comment] 2013-08-14 18:42
Still not working for me.  I can't re-open issues in your repo.  I attempted to clear the cache.

To compile:
git fetch origin master
git stash
git reset --hard FETCH_HEAD
git stash pop
make clean
../build.sh

Compiling succeeds.

build.sh is located one directory above the git dir.

build.sh: https://gist.github.com/MattDunbar/966cac81d7266e6ae7c2

You can see that I'm up to date with git here: https://gist.github.com/MattDunbar/3471c94901608bb0c008
